# Generated by Django 4.2.3 on 2023-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('cashflow_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cashflow_subtype', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('broker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('holding_name', models.CharField(blank=True, max_length=255, null=True)),
                ('holding_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('price_date', models.DateField(blank=True, null=True)),
                ('total_contribution', models.FloatField(blank=True, null=True)),
                ('holding_market_value_holding_currency', models.FloatField(blank=True, null=True)),
                ('holding_market_value_policy_currency', models.FloatField(blank=True, null=True)),
                ('isin', models.CharField(blank=True, max_length=255, null=True)),
                ('sedol', models.CharField(blank=True, max_length=255, null=True)),
                ('book_cost', models.FloatField(blank=True, null=True)),
                ('gain_loss', models.FloatField(blank=True, null=True)),
                ('holding_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('trust', models.CharField(blank=True, max_length=255, null=True)),
                ('surrender_penalty', models.FloatField(blank=True, null=True)),
                ('max_partial_value', models.FloatField(blank=True, null=True)),
                ('surrender_value', models.FloatField(blank=True, null=True)),
                ('sub_policies', models.TextField(blank=True, null=True)),
                ('policy_basis', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_comments', models.TextField(blank=True, null=True)),
                ('transaction_debit_amount', models.FloatField(blank=True, null=True)),
                ('transaction_credit_amount', models.FloatField(blank=True, null=True)),
                ('transaction_amount', models.FloatField(blank=True, null=True)),
                ('transaction_currency', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegularPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_contribution', models.FloatField(blank=True, null=True)),
                ('single_contribution', models.FloatField(blank=True, null=True)),
                ('policy_term', models.IntegerField(blank=True, null=True)),
                ('contribution_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution_due_date', models.DateField(blank=True, null=True)),
                ('contribution_received_date', models.DateField(blank=True, null=True)),
                ('next_contribution_date', models.DateField(blank=True, null=True)),
                ('last_contribution_date', models.DateField(blank=True, null=True)),
                ('contribution_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('arrears', models.FloatField(blank=True, null=True)),
                ('contribution_due', models.FloatField(blank=True, null=True)),
                ('contribution_received', models.FloatField(blank=True, null=True)),
                ('number_premiums_missed', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
