# Generated by Django 4.2.3 on 2023-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='db_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
