# Generated by Django 4.2.3 on 2023-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_policy_db_entry_date_policy_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
