# Generated by Django 4.2.3 on 2023-07-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='arrear_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='arrears',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_received',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contribution_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_contribution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='next_contribution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='number_premiums_missed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='regular_contribution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='single_contribution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
