# Generated by Django 4.2.3 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_policy_arrear_status_policy_arrears_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RL360Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding', models.CharField(max_length=255)),
                ('cash_holding', models.CharField(max_length=255)),
                ('policy', models.CharField(max_length=255)),
                ('premium_history', models.CharField(max_length=255)),
                ('cash_transaction', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='withdrawals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
