# Generated by Django 4.2.3 on 2023-07-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_financialaccount_holdings_policy_account_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='provider',
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
