# Generated by Django 4.2.3 on 2023-07-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_holdings_provider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialAccount',
            new_name='FinancialAccountModel',
        ),
        migrations.RenameModel(
            old_name='Holdings',
            new_name='HoldingsModel',
        ),
    ]
