# Generated by Django 4.2.3 on 2023-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_financialaccount_financialaccountmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountmodel',
            name='premium_holiday_commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountmodel',
            name='premium_holiday_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountmodel',
            name='premium_holiday_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
