# Generated by Django 4.2.3 on 2023-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_financialaccountmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountmodel',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
