# Generated by Django 4.2.3 on 2023-07-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_financialaccountmodel_provider_id_policy_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rl360records',
            name='cash_holding',
            field=models.FileField(null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='rl360records',
            name='cash_transaction',
            field=models.FileField(null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='rl360records',
            name='holding',
            field=models.FileField(null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='rl360records',
            name='policy',
            field=models.FileField(null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='rl360records',
            name='premium_history',
            field=models.FileField(null=True, upload_to='records/'),
        ),
    ]
