# Generated by Django 4.2.3 on 2023-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_rl360records_cash_holding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappedFinancialAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('policy_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('sub_policies', models.TextField(blank=True, null=True)),
                ('sub_product_type', models.TextField(blank=True, null=True)),
                ('policy_basis', models.CharField(blank=True, max_length=255, null=True)),
                ('business_split', models.CharField(blank=True, max_length=255, null=True)),
                ('account_status', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_contribution', models.FloatField(blank=True, null=True)),
                ('lumpsum_contribution', models.FloatField(blank=True, null=True)),
                ('policy_term', models.IntegerField(blank=True, null=True)),
                ('contribution_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('next_contribution_date', models.DateField(blank=True, null=True)),
                ('last_contribution_date', models.DateField(blank=True, null=True)),
                ('number_premiums_missed', models.IntegerField(blank=True, null=True)),
                ('arrear_status', models.CharField(blank=True, max_length=255, null=True)),
                ('premium_holiday_status', models.CharField(blank=True, max_length=255, null=True)),
                ('premium_holiday_commencement_date', models.DateField(blank=True, null=True)),
                ('premium_holiday_end_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
